### ISSUE TITLE
Google.Units matches on text in text code block

### ISSUE THREAD

**Issue by ggiesen** [errata-ai/Google#13]
Given the following rST text:

```
#. Configure the grain values to be accepted:

   Place a file named like the grain in the ``autosign_grains_dir`` and write
   the values that should be accepted automatically inside that file. For
   example, to automatically accept minions based on their uuid, create a
   file named:

   .. code-block:: text
      :caption: /etc/salt/autosign_grains/uuid

      8f7d68e2-30c5-40c6-b84a-df7e978a03ee
      1d3c5473-1fbc-479e-b0c7-877705a0730f

   The Salt master is now set up to accept minions with either of the two
   specified uuids. Multiple values must always be written into separate
   lines. Lines starting with a # are ignored.
```

which renders to the following HTML with `rst2html`:

```
<li><p class="first">Configure the grain values to be accepted:</p>
<p>Place a file named like the grain in the <code class="docutils literal notranslate"><span class="pre">autosign_grains_dir</span></code> and write
the values that should be accepted automatically inside that file. For
example, to automatically accept minions based on their uuid, create a
file named:</p>
<div class="literal-block-wrapper docutils container" id="id3">
<div class="code-block-caption"><span class="caption-text">/etc/salt/autosign_grains/uuid</span><a class="headerlink" href="#id3" title="Permalink to this code">¶</a></div>
<div class="highlight-text notranslate"><div class="highlight"><pre><span></span>8f7d68e2-30c5-40c6-b84a-df7e978a03ee
1d3c5473-1fbc-479e-b0c7-877705a0730f
</pre></div>
</div>
</div>
<p>The Salt master is now set up to accept minions with either of the two
specified uuids. Multiple values must always be written into separate
lines. Lines starting with a # are ignored.</p>
</li>
```

Vale is matching Google.Units on the text code block:

```
$ vale docs/topics/grains.rst

 docs/topics/grains.rst
 121:9  error  Put a nonbreaking space         Google.Units
               between the number and the
               unit in '7d'.
 122:7  error  Put a nonbreaking space         Google.Units
               between the number and the
               unit in '1d'.

✖ 2 errors, 0 warnings and 0 suggestions in 1 file.
```

**Comment by jdkato** [comment]
What arguments are you passing to`rst2html`?

When I  run the that text, as-is, through `rst2html`, I receive an error: `Error in "code-block" directive: unknown option: "caption".`.

Also, re: https://github.com/errata-ai/Google/pull/14, changing the scope to avoid this isn't ideal for two reasons: (1) the default scope, `text`, should already ignore code blocks (syntax errors notwithstanding) and (2) `sentence` requires segmentation which comes with performance overhead.

**Comment by ggiesen** [comment]
You can view the original source here:

https://gitlab.com/saltstack/open/docs/salt-user-guide/-/blob/master/docs/topics/grains.rst

#14 was premature, I had thought that scoping actually solved the problem, but it turns out it didn't so I marked it WIP.

**Comment by jdkato** [comment]
I've pushed a workaround fix into the main Vale repo, so this should be fixed in the next release of Vale.

**Comment by ggiesen** [comment]
I built vale from master for a quick test and it seems to solve my issue. I look forward to the next release. Thanks for your help on this.

**Comment by jdkato** [comment]
[v2.10.5](https://github.com/errata-ai/vale/releases/tag/v2.10.5) is out now.

**Comment by amthorn** [comment]
I'm observing this same issue but for Google.Quotes I'm using vale version 2.10.5.

**Comment by jdkato** [comment]
@amthorn: That syntax isn't supported by [CommonMark](https://commonmark.org/) (the flavor of Markdown that Vale and GitHub itself use). If you can add a space between `???+ Example` and the opening backticks or remove the indentation, it should work.
