### ISSUE TITLE
Markdown Footnotes can start with an uppercase character

### ISSUE THREAD

**Issue by davidsneighbour** [errata-ai/Google#22]
I have the following Markdown text:

```markdown
[^1]: Careful here --- You will have to first **check out** ...
```

Vale complains about `Careful` having to be `careful` (Google.Colon). I do not agree with this and I think this is not a "colon rule thing". This markup will be transformed into the text for the footnote of the reference markdown `some text [^1] and more text` in [Goldmark](https://github.com/yuin/goldmark). 

I think footnotes in the text should be allowed to start with an uppercase. I also don't want to disable the rule completely, because I think in the normal text flow a colon should be followed by a lowercase character. 

Is this a "real world issue" or am I just missing an easy workaround?

Maybe exchange the 

```yaml
tokens:
  - ':\s[A-Z]'
```

with something like

```yaml
tokens:
  - (!])':\s[A-Z]'
```

might work? I can see cases though where someone might write "something [something]: Wrong case" that should fail. 

Please advise if it's a bug or an issue only _I_ have :)

**Comment by jdkato** [comment]
The footnote extension will be enabled in the next release of Vale, which will fix this issue.
