### ISSUE TITLE
Adding "B2B" to accept.txt doesn't create an exception to Google.Units

### ISSUE THREAD

**Issue by kosara-golemshinska** [errata-ai/Google#27]
OS: macOS Ventura
Install method: Homebrew
Vale version: 2.24.4

`Google.Units` returns the error `Put a nonbreaking space between the number and the unit in '2B'.` even when "B2B" is added to `accept.txt`.

I upgraded to the latest version of the Vale CLI just in case but the issue persists.

I've set up the Vale GitHub action in one repository, where the same issue appears every time "B2B" is used, despite it being in `accept.txt`.

**Comment by jdkato** [comment]
This should be fixed in the latest release.
