### ISSUE TITLE
Issue with AKA rule in Wordlist

### ISSUE THREAD

**Issue by danielhspang** [errata-ai/Google#29]
We're seeing the following error when running Vale from our github action
```
 /bin/vale install Google https://github.com/errata-ai/Google/releases/latest/download/Google.zip
/bin/vale install proselint https://github.com/errata-ai/proselint/releases/latest/download/proselint.zip
Error: {
  "Line": 28,
  "Path": "/github/workspace/.github/styles/Google/WordList.yml",
  "Text": "capture group not supported; use '(?:' instead of '('",
  "Code": "E201",
  "Span": 3
}
```

It seems the AKA rule added in https://github.com/errata-ai/Google/pull/23 is causing this issue. Using an older version of Google styles (i.e. https://github.com/errata-ai/Google/releases/download/v0.3.3/Google.zip) fixed the issue for us (as it does not have the AKA rule) but we would no longer receive the latest Google style updates.

We are using `errata-ai/vale-action@v1.4.2`

**Comment by jdkato** [comment]
Should be fixed now.
