### ISSUE TITLE
"Use select for check" for an "Please check back later" phrase

### ISSUE THREAD

**Issue by davidsneighbour** [errata-ai/Google#33]
The phrase 

"Please check back later." 

results in "check" being warned about with 

Use 'select' instead of 'check'.Vale[Google.WordList](https://developers.google.com/style/word-list)

Adding "check back" to my accept.txt did not solve the issue. Is there any way to mark this allowed or fix the rule altogether?

**Comment by pwalleni** [comment]
This rule also triggers incorrectly for us. A solution would be welcome.

**Comment by jdkato** [comment]
I removed the term from `WordList.yml`. Cases like this probably need their own (suggestion-level) rule where the `message` can be more clear/specific.
