### ISSUE TITLE
Extending the exception list for Google.Acronyms

### ISSUE THREAD

**Issue by jahagirdar** [errata-ai/Google#34]
The acronyms file has a list of basic acronyms for which an Info will not be generated.
This list does not contain acronyms specific to my sector.
e.g. i am in chip design field and my document is littered with FPGA, ASIC, AHB, AXI, ARM, DRAM, SRAM, DMA, DDR, SDR etc.
Is there a way for me to maintain a personal exception file instead to modifying google's style file?

**Comment by jdkato** [comment]
Yes, create a [vocabulary](https://vale.sh/docs/topics/vocab/).
