### ISSUE TITLE
AMPM matches non-time text

### ISSUE THREAD

**Issue by datawookie** [errata-ai/Google#37]
Hi!

I've been using these rules and they have greatly improved my text. However, I came across something unexpected. The AMPM rule is being activated by text like "5 ampoules". Looking at the rule I can see that this text would match the last REGEX, `'\d{1,2} ?[aApP]\.[mM]\.'`.

Is this the expected behaviour?

Best regards, Andrew.

**Comment by jdkato** [comment]
This should be fixed in the next release.

**Comment by datawookie** [comment]
Brilliant. Thanks for sorting so quickly!
