### ISSUE TITLE
Capitalisation rule and possesive 

### ISSUE THREAD

**Issue by tomato42** [errata-ai/Google#5]
I have a heading with a possessive form that uses an apostrophe.

The literal header in rst file is:
```
Client's key share and finish
-----------------------------
```

it's getting marked by the HeadingPunctuation rule:
https://github.com/errata-ai/Google/blob/master/Google/HeadingPunctuation.yml

Shouldn't apostrophes be allowed in headings?

**Comment by jdkato** [comment]
Yes, this is a bug -- I've added a test that reproduces the issue and I'll look into fixing it soon.

**Comment by jdkato** [comment]
This will be fixed in the next release of Vale -- I'll close the issue once the release is available.
