### ISSUE TITLE
Google.Spacing err on .NET

### ISSUE THREAD

**Issue by ricovitch** [errata-ai/Google#6]
This is exactly the same issue that has been reported and solved on Microsoft.Spacing rules here : https://github.com/errata-ai/Microsoft/issues/14

repro:

`echo 'The latest version of .NET Core is awesome' | vale --no-wrap -ext='.md'`

result:
```
stdin.md
 1:23  error  '.N' should have one space.  Google.Spacing
```

**Comment by jdkato** [comment]
This is fixed in v0.3.2.
